name: Deploy to Azure VM

on:
  push:
    branches:
      - main # The branch to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 74.225.3.16
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /home/azureuser && chmod +x deploy.sh && ./deploy.sh